// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mosque-dashboard.proto

package com.mujeeb.mosquedashboard.grpc;

public interface HijriAdjustmentUpdateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.mujeeb.mosquedashboard.grpc.HijriAdjustmentUpdateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 hijriAdjustment = 1;</code>
   * @return The hijriAdjustment.
   */
  int getHijriAdjustment();
}
