// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mosque-dashboard.proto

package com.mujeeb.mosquedashboard.grpc;

public interface HijriAdjustmentUpdateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.mujeeb.mosquedashboard.grpc.HijriAdjustmentUpdateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.mujeeb.mosquedashboard.grpc.AuthData authData = 1;</code>
   * @return Whether the authData field is set.
   */
  boolean hasAuthData();
  /**
   * <code>.com.mujeeb.mosquedashboard.grpc.AuthData authData = 1;</code>
   * @return The authData.
   */
  com.mujeeb.mosquedashboard.grpc.AuthData getAuthData();
  /**
   * <code>.com.mujeeb.mosquedashboard.grpc.AuthData authData = 1;</code>
   */
  com.mujeeb.mosquedashboard.grpc.AuthDataOrBuilder getAuthDataOrBuilder();

  /**
   * <code>int32 hijriAdjustment = 2;</code>
   * @return The hijriAdjustment.
   */
  int getHijriAdjustment();
}
