// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mosque-dashboard.proto

package com.mujeeb.mosquedashboard.grpc;

@SuppressWarnings("deprecation")
public final class MosqueDashboardProto {
  private MosqueDashboardProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mujeeb_mosquedashboard_grpc_NamazTime_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_mujeeb_mosquedashboard_grpc_NamazTime_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mujeeb_mosquedashboard_grpc_GetDataForMobileAppRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_mujeeb_mosquedashboard_grpc_GetDataForMobileAppRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mujeeb_mosquedashboard_grpc_HijriAdjustmentUpdateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_mujeeb_mosquedashboard_grpc_HijriAdjustmentUpdateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mujeeb_mosquedashboard_grpc_ScreenSaverStateUpdateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_mujeeb_mosquedashboard_grpc_ScreenSaverStateUpdateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mujeeb_mosquedashboard_grpc_StringContainer_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_mujeeb_mosquedashboard_grpc_StringContainer_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mujeeb_mosquedashboard_grpc_GenericReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_mujeeb_mosquedashboard_grpc_GenericReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mujeeb_mosquedashboard_grpc_EmptyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_mujeeb_mosquedashboard_grpc_EmptyRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026mosque-dashboard.proto\022\037com.mujeeb.mos" +
      "quedashboard.grpc\"@\n\tNamazTime\022\025\n\rnamazT" +
      "imeName\030\001 \001(\t\022\014\n\004hour\030\002 \001(\005\022\016\n\006minute\030\003 " +
      "\001(\005\"\264\004\n\032GetDataForMobileAppRequest\022<\n\010fa" +
      "jrTime\030\001 \001(\0132*.com.mujeeb.mosquedashboar" +
      "d.grpc.NamazTime\022<\n\010zuhrTime\030\002 \001(\0132*.com" +
      ".mujeeb.mosquedashboard.grpc.NamazTime\022;" +
      "\n\007asrTime\030\003 \001(\0132*.com.mujeeb.mosquedashb" +
      "oard.grpc.NamazTime\022<\n\010ishaTime\030\004 \001(\0132*." +
      "com.mujeeb.mosquedashboard.grpc.NamazTim" +
      "e\022=\n\tjumuaTime\030\005 \001(\0132*.com.mujeeb.mosque" +
      "dashboard.grpc.NamazTime\022E\n\021screenSaverO" +
      "nTime\030\006 \001(\0132*.com.mujeeb.mosquedashboard" +
      ".grpc.NamazTime\022F\n\022screenSaverOffTime\030\007 " +
      "\001(\0132*.com.mujeeb.mosquedashboard.grpc.Na" +
      "mazTime\022\027\n\017hijriAdjustment\030\010 \001(\005\022\021\n\thijr" +
      "iDate\030\t \001(\005\022\022\n\nhijriMonth\030\n \001(\t\022\021\n\thijri" +
      "Year\030\013 \001(\005\"7\n\034HijriAdjustmentUpdateReque" +
      "st\022\027\n\017hijriAdjustment\030\001 \001(\005\"-\n\035ScreenSav" +
      "erStateUpdateRequest\022\014\n\004isOn\030\001 \001(\010\"\036\n\017St" +
      "ringContainer\022\013\n\003str\030\001 \001(\t\"9\n\014GenericRep" +
      "ly\022\023\n\013description\030\001 \001(\t\022\024\n\014responseCode\030" +
      "\002 \001(\005\"\016\n\014EmptyRequest2\351\007\n\026MosqueDashboar" +
      "dService\022\203\001\n\023GetDataForMobileApp\022-.com.m" +
      "ujeeb.mosquedashboard.grpc.EmptyRequest\032" +
      ";.com.mujeeb.mosquedashboard.grpc.GetDat" +
      "aForMobileAppRequest\"\000\022n\n\017UpdateNamazTim" +
      "e\022*.com.mujeeb.mosquedashboard.grpc.Nama" +
      "zTime\032-.com.mujeeb.mosquedashboard.grpc." +
      "GenericReply\"\000\022\207\001\n\025ChangeHijriAdjustment" +
      "\022=.com.mujeeb.mosquedashboard.grpc.Hijri" +
      "AdjustmentUpdateRequest\032-.com.mujeeb.mos" +
      "quedashboard.grpc.GenericReply\"\000\022k\n\tTest" +
      "Audio\022-.com.mujeeb.mosquedashboard.grpc." +
      "EmptyRequest\032-.com.mujeeb.mosquedashboar" +
      "d.grpc.GenericReply\"\000\022\211\001\n\026ChangeScreenSa" +
      "verState\022>.com.mujeeb.mosquedashboard.gr" +
      "pc.ScreenSaverStateUpdateRequest\032-.com.m" +
      "ujeeb.mosquedashboard.grpc.GenericReply\"" +
      "\000\022p\n\013SetDateTime\0220.com.mujeeb.mosquedash" +
      "board.grpc.StringContainer\032-.com.mujeeb." +
      "mosquedashboard.grpc.GenericReply\"\000\022o\n\rR" +
      "estartSystem\022-.com.mujeeb.mosquedashboar" +
      "d.grpc.EmptyRequest\032-.com.mujeeb.mosqued" +
      "ashboard.grpc.GenericReply\"\000\022s\n\016HasDateC" +
      "hanged\022-.com.mujeeb.mosquedashboard.grpc" +
      ".EmptyRequest\0320.com.mujeeb.mosquedashboa" +
      "rd.grpc.StringContainer\"\000B?\n\037com.mujeeb." +
      "mosquedashboard.grpcB\024MosqueDashboardPro" +
      "toP\001\242\002\003HLWb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_mujeeb_mosquedashboard_grpc_NamazTime_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_mujeeb_mosquedashboard_grpc_NamazTime_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_mujeeb_mosquedashboard_grpc_NamazTime_descriptor,
        new java.lang.String[] { "NamazTimeName", "Hour", "Minute", });
    internal_static_com_mujeeb_mosquedashboard_grpc_GetDataForMobileAppRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_mujeeb_mosquedashboard_grpc_GetDataForMobileAppRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_mujeeb_mosquedashboard_grpc_GetDataForMobileAppRequest_descriptor,
        new java.lang.String[] { "FajrTime", "ZuhrTime", "AsrTime", "IshaTime", "JumuaTime", "ScreenSaverOnTime", "ScreenSaverOffTime", "HijriAdjustment", "HijriDate", "HijriMonth", "HijriYear", });
    internal_static_com_mujeeb_mosquedashboard_grpc_HijriAdjustmentUpdateRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_mujeeb_mosquedashboard_grpc_HijriAdjustmentUpdateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_mujeeb_mosquedashboard_grpc_HijriAdjustmentUpdateRequest_descriptor,
        new java.lang.String[] { "HijriAdjustment", });
    internal_static_com_mujeeb_mosquedashboard_grpc_ScreenSaverStateUpdateRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_mujeeb_mosquedashboard_grpc_ScreenSaverStateUpdateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_mujeeb_mosquedashboard_grpc_ScreenSaverStateUpdateRequest_descriptor,
        new java.lang.String[] { "IsOn", });
    internal_static_com_mujeeb_mosquedashboard_grpc_StringContainer_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_mujeeb_mosquedashboard_grpc_StringContainer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_mujeeb_mosquedashboard_grpc_StringContainer_descriptor,
        new java.lang.String[] { "Str", });
    internal_static_com_mujeeb_mosquedashboard_grpc_GenericReply_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_mujeeb_mosquedashboard_grpc_GenericReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_mujeeb_mosquedashboard_grpc_GenericReply_descriptor,
        new java.lang.String[] { "Description", "ResponseCode", });
    internal_static_com_mujeeb_mosquedashboard_grpc_EmptyRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_com_mujeeb_mosquedashboard_grpc_EmptyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_mujeeb_mosquedashboard_grpc_EmptyRequest_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
