// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mosque-dashboard.proto

package com.mujeeb.mosquedashboard.grpc;

public interface ScreenSaverStateUpdateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.mujeeb.mosquedashboard.grpc.ScreenSaverStateUpdateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool isOn = 1;</code>
   * @return The isOn.
   */
  boolean getIsOn();
}
