// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mosque-dashboard.proto

package com.mujeeb.mosquedashboard.grpc;

public interface StringContainerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.mujeeb.mosquedashboard.grpc.StringContainer)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string str = 1;</code>
   * @return The str.
   */
  java.lang.String getStr();
  /**
   * <code>string str = 1;</code>
   * @return The bytes for str.
   */
  com.google.protobuf.ByteString
      getStrBytes();
}
