// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mosque-dashboard.proto

package com.mujeeb.mosquedashboard.grpc;

/**
 * Protobuf type {@code com.mujeeb.mosquedashboard.grpc.StringContainer}
 */
@SuppressWarnings("deprecation")
public final class StringContainer extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.mujeeb.mosquedashboard.grpc.StringContainer)
    StringContainerOrBuilder {
private static final long serialVersionUID = 0L;
  // Use StringContainer.newBuilder() to construct.
  private StringContainer(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private StringContainer() {
    str_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new StringContainer();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private StringContainer(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.mujeeb.mosquedashboard.grpc.AuthData.Builder subBuilder = null;
            if (authData_ != null) {
              subBuilder = authData_.toBuilder();
            }
            authData_ = input.readMessage(com.mujeeb.mosquedashboard.grpc.AuthData.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(authData_);
              authData_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            str_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
//      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.mujeeb.mosquedashboard.grpc.MosqueDashboardProto.internal_static_com_mujeeb_mosquedashboard_grpc_StringContainer_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.mujeeb.mosquedashboard.grpc.MosqueDashboardProto.internal_static_com_mujeeb_mosquedashboard_grpc_StringContainer_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.mujeeb.mosquedashboard.grpc.StringContainer.class, com.mujeeb.mosquedashboard.grpc.StringContainer.Builder.class);
  }

  public static final int AUTHDATA_FIELD_NUMBER = 1;
  private com.mujeeb.mosquedashboard.grpc.AuthData authData_;
  /**
   * <code>.com.mujeeb.mosquedashboard.grpc.AuthData authData = 1;</code>
   * @return Whether the authData field is set.
   */
  @java.lang.Override
  public boolean hasAuthData() {
    return authData_ != null;
  }
  /**
   * <code>.com.mujeeb.mosquedashboard.grpc.AuthData authData = 1;</code>
   * @return The authData.
   */
  @java.lang.Override
  public com.mujeeb.mosquedashboard.grpc.AuthData getAuthData() {
    return authData_ == null ? com.mujeeb.mosquedashboard.grpc.AuthData.getDefaultInstance() : authData_;
  }
  /**
   * <code>.com.mujeeb.mosquedashboard.grpc.AuthData authData = 1;</code>
   */
  @java.lang.Override
  public com.mujeeb.mosquedashboard.grpc.AuthDataOrBuilder getAuthDataOrBuilder() {
    return getAuthData();
  }

  public static final int STR_FIELD_NUMBER = 2;
  private volatile java.lang.Object str_;
  /**
   * <code>string str = 2;</code>
   * @return The str.
   */
  @java.lang.Override
  public java.lang.String getStr() {
    java.lang.Object ref = str_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      str_ = s;
      return s;
    }
  }
  /**
   * <code>string str = 2;</code>
   * @return The bytes for str.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStrBytes() {
    java.lang.Object ref = str_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      str_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (authData_ != null) {
      output.writeMessage(1, getAuthData());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(str_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, str_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (authData_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getAuthData());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(str_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, str_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.mujeeb.mosquedashboard.grpc.StringContainer)) {
      return super.equals(obj);
    }
    com.mujeeb.mosquedashboard.grpc.StringContainer other = (com.mujeeb.mosquedashboard.grpc.StringContainer) obj;

    if (hasAuthData() != other.hasAuthData()) return false;
    if (hasAuthData()) {
      if (!getAuthData()
          .equals(other.getAuthData())) return false;
    }
    if (!getStr()
        .equals(other.getStr())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @SuppressWarnings("unchecked")
@java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasAuthData()) {
      hash = (37 * hash) + AUTHDATA_FIELD_NUMBER;
      hash = (53 * hash) + getAuthData().hashCode();
    }
    hash = (37 * hash) + STR_FIELD_NUMBER;
    hash = (53 * hash) + getStr().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.mujeeb.mosquedashboard.grpc.StringContainer parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mujeeb.mosquedashboard.grpc.StringContainer parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mujeeb.mosquedashboard.grpc.StringContainer parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mujeeb.mosquedashboard.grpc.StringContainer parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mujeeb.mosquedashboard.grpc.StringContainer parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.mujeeb.mosquedashboard.grpc.StringContainer parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.mujeeb.mosquedashboard.grpc.StringContainer parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.mujeeb.mosquedashboard.grpc.StringContainer parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.mujeeb.mosquedashboard.grpc.StringContainer parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.mujeeb.mosquedashboard.grpc.StringContainer parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.mujeeb.mosquedashboard.grpc.StringContainer parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.mujeeb.mosquedashboard.grpc.StringContainer parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.mujeeb.mosquedashboard.grpc.StringContainer prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.mujeeb.mosquedashboard.grpc.StringContainer}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.mujeeb.mosquedashboard.grpc.StringContainer)
      com.mujeeb.mosquedashboard.grpc.StringContainerOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mujeeb.mosquedashboard.grpc.MosqueDashboardProto.internal_static_com_mujeeb_mosquedashboard_grpc_StringContainer_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mujeeb.mosquedashboard.grpc.MosqueDashboardProto.internal_static_com_mujeeb_mosquedashboard_grpc_StringContainer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mujeeb.mosquedashboard.grpc.StringContainer.class, com.mujeeb.mosquedashboard.grpc.StringContainer.Builder.class);
    }

    // Construct using com.mujeeb.mosquedashboard.grpc.StringContainer.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (authDataBuilder_ == null) {
        authData_ = null;
      } else {
        authData_ = null;
        authDataBuilder_ = null;
      }
      str_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.mujeeb.mosquedashboard.grpc.MosqueDashboardProto.internal_static_com_mujeeb_mosquedashboard_grpc_StringContainer_descriptor;
    }

    @java.lang.Override
    public com.mujeeb.mosquedashboard.grpc.StringContainer getDefaultInstanceForType() {
      return com.mujeeb.mosquedashboard.grpc.StringContainer.getDefaultInstance();
    }

    @java.lang.Override
    public com.mujeeb.mosquedashboard.grpc.StringContainer build() {
      com.mujeeb.mosquedashboard.grpc.StringContainer result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.mujeeb.mosquedashboard.grpc.StringContainer buildPartial() {
      com.mujeeb.mosquedashboard.grpc.StringContainer result = new com.mujeeb.mosquedashboard.grpc.StringContainer(this);
      if (authDataBuilder_ == null) {
        result.authData_ = authData_;
      } else {
        result.authData_ = authDataBuilder_.build();
      }
      result.str_ = str_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.mujeeb.mosquedashboard.grpc.StringContainer) {
        return mergeFrom((com.mujeeb.mosquedashboard.grpc.StringContainer)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.mujeeb.mosquedashboard.grpc.StringContainer other) {
      if (other == com.mujeeb.mosquedashboard.grpc.StringContainer.getDefaultInstance()) return this;
      if (other.hasAuthData()) {
        mergeAuthData(other.getAuthData());
      }
      if (!other.getStr().isEmpty()) {
        str_ = other.str_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.mujeeb.mosquedashboard.grpc.StringContainer parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.mujeeb.mosquedashboard.grpc.StringContainer) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.mujeeb.mosquedashboard.grpc.AuthData authData_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.mujeeb.mosquedashboard.grpc.AuthData, com.mujeeb.mosquedashboard.grpc.AuthData.Builder, com.mujeeb.mosquedashboard.grpc.AuthDataOrBuilder> authDataBuilder_;
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.AuthData authData = 1;</code>
     * @return Whether the authData field is set.
     */
    public boolean hasAuthData() {
      return authDataBuilder_ != null || authData_ != null;
    }
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.AuthData authData = 1;</code>
     * @return The authData.
     */
    public com.mujeeb.mosquedashboard.grpc.AuthData getAuthData() {
      if (authDataBuilder_ == null) {
        return authData_ == null ? com.mujeeb.mosquedashboard.grpc.AuthData.getDefaultInstance() : authData_;
      } else {
        return authDataBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.AuthData authData = 1;</code>
     */
    public Builder setAuthData(com.mujeeb.mosquedashboard.grpc.AuthData value) {
      if (authDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        authData_ = value;
        onChanged();
      } else {
        authDataBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.AuthData authData = 1;</code>
     */
    public Builder setAuthData(
        com.mujeeb.mosquedashboard.grpc.AuthData.Builder builderForValue) {
      if (authDataBuilder_ == null) {
        authData_ = builderForValue.build();
        onChanged();
      } else {
        authDataBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.AuthData authData = 1;</code>
     */
    public Builder mergeAuthData(com.mujeeb.mosquedashboard.grpc.AuthData value) {
      if (authDataBuilder_ == null) {
        if (authData_ != null) {
          authData_ =
            com.mujeeb.mosquedashboard.grpc.AuthData.newBuilder(authData_).mergeFrom(value).buildPartial();
        } else {
          authData_ = value;
        }
        onChanged();
      } else {
        authDataBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.AuthData authData = 1;</code>
     */
    public Builder clearAuthData() {
      if (authDataBuilder_ == null) {
        authData_ = null;
        onChanged();
      } else {
        authData_ = null;
        authDataBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.AuthData authData = 1;</code>
     */
    public com.mujeeb.mosquedashboard.grpc.AuthData.Builder getAuthDataBuilder() {
      
      onChanged();
      return getAuthDataFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.AuthData authData = 1;</code>
     */
    public com.mujeeb.mosquedashboard.grpc.AuthDataOrBuilder getAuthDataOrBuilder() {
      if (authDataBuilder_ != null) {
        return authDataBuilder_.getMessageOrBuilder();
      } else {
        return authData_ == null ?
            com.mujeeb.mosquedashboard.grpc.AuthData.getDefaultInstance() : authData_;
      }
    }
    /**
     * <code>.com.mujeeb.mosquedashboard.grpc.AuthData authData = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.mujeeb.mosquedashboard.grpc.AuthData, com.mujeeb.mosquedashboard.grpc.AuthData.Builder, com.mujeeb.mosquedashboard.grpc.AuthDataOrBuilder> 
        getAuthDataFieldBuilder() {
      if (authDataBuilder_ == null) {
        authDataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.mujeeb.mosquedashboard.grpc.AuthData, com.mujeeb.mosquedashboard.grpc.AuthData.Builder, com.mujeeb.mosquedashboard.grpc.AuthDataOrBuilder>(
                getAuthData(),
                getParentForChildren(),
                isClean());
        authData_ = null;
      }
      return authDataBuilder_;
    }

    private java.lang.Object str_ = "";
    /**
     * <code>string str = 2;</code>
     * @return The str.
     */
    public java.lang.String getStr() {
      java.lang.Object ref = str_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        str_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string str = 2;</code>
     * @return The bytes for str.
     */
    public com.google.protobuf.ByteString
        getStrBytes() {
      java.lang.Object ref = str_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        str_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string str = 2;</code>
     * @param value The str to set.
     * @return This builder for chaining.
     */
    public Builder setStr(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      str_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string str = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearStr() {
      
      str_ = getDefaultInstance().getStr();
      onChanged();
      return this;
    }
    /**
     * <code>string str = 2;</code>
     * @param value The bytes for str to set.
     * @return This builder for chaining.
     */
    public Builder setStrBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      str_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.mujeeb.mosquedashboard.grpc.StringContainer)
  }

  // @@protoc_insertion_point(class_scope:com.mujeeb.mosquedashboard.grpc.StringContainer)
  private static final com.mujeeb.mosquedashboard.grpc.StringContainer DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.mujeeb.mosquedashboard.grpc.StringContainer();
  }

  public static com.mujeeb.mosquedashboard.grpc.StringContainer getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<StringContainer>
      PARSER = new com.google.protobuf.AbstractParser<StringContainer>() {
    @java.lang.Override
    public StringContainer parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new StringContainer(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<StringContainer> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<StringContainer> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.mujeeb.mosquedashboard.grpc.StringContainer getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

