// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mosque-dashboard.proto

package com.mujeeb.mosquedashboard.grpc;

public interface StringContainerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.mujeeb.mosquedashboard.grpc.StringContainer)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.mujeeb.mosquedashboard.grpc.AuthData authData = 1;</code>
   * @return Whether the authData field is set.
   */
  boolean hasAuthData();
  /**
   * <code>.com.mujeeb.mosquedashboard.grpc.AuthData authData = 1;</code>
   * @return The authData.
   */
  com.mujeeb.mosquedashboard.grpc.AuthData getAuthData();
  /**
   * <code>.com.mujeeb.mosquedashboard.grpc.AuthData authData = 1;</code>
   */
  com.mujeeb.mosquedashboard.grpc.AuthDataOrBuilder getAuthDataOrBuilder();

  /**
   * <code>string str = 2;</code>
   * @return The str.
   */
  java.lang.String getStr();
  /**
   * <code>string str = 2;</code>
   * @return The bytes for str.
   */
  com.google.protobuf.ByteString
      getStrBytes();
}
